// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) (User, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetAccountByIdForUpdate(ctx context.Context, id int64) (Account, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]Account, error)
	GetAllTransferFromAAccount(ctx context.Context, arg GetAllTransferFromAAccountParams) ([]Transfer, error)
	GetAllTransfersBetweenTwoAccounts(ctx context.Context, arg GetAllTransfersBetweenTwoAccountsParams) ([]Transfer, error)
	GetEntriesByAccountId(ctx context.Context, arg GetEntriesByAccountIdParams) ([]Entry, error)
	GetEntryById(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransferById(ctx context.Context, id int64) (Transfer, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersAccounts(ctx context.Context, username string) ([]Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateSession(ctx context.Context, id uuid.UUID) error
	UpdateUserEmailVerification(ctx context.Context, arg UpdateUserEmailVerificationParams) (User, error)
}

var _ Querier = (*Queries)(nil)
